name: BoomPlugin
version: '${project.version}'
main: com.blub.testplugin.TestPlugin
api-version: 1.18
authors: [ Blub ]
description: Boom? Yes Rico boom!
commands:
  boom:
    description: Creates an expolsion
  chickenboom:
    description: Creates an explosion of chickens
permissions:
  boomplugin.*:
    description: BoomPlugin
    children:
      boomplugin.boom: true
      boomplugin.chickenboom: true
    boomplugin.boom:
      description: Creates an explosion
      default: op
    boomplugin.chickenboom:
      description: Creates an explosion of chickens
      default: op